# Generated by Django 4.2.6 on 2023-11-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
