# Generated by Django 4.2.6 on 2023-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_todolist_archived_todolist_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='binned',
            field=models.BooleanField(default=False),
        ),
    ]
