# Generated by Django 4.2.6 on 2023-11-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_todolist_binned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='binned',
        ),
    ]
