# Generated by Django 4.2.6 on 2023-11-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_todolist_binned'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='color',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
